/**
 * Inject the social-preview and structured-data tags into every page head.
 * Spec: docs/specs/seo.md §3
 *
 * Run once, by hand, and reviewed as a diff — **not** part of the build. The tags then
 * live in the HTML where anyone can read and edit them, which is the point: a generated
 * head is one more thing between a contributor and the thing they want to change.
 *
 * `www/seo.test.mjs` is what keeps them honest afterwards, and it is the thing that runs
 * on every commit.
 *
 * Usage:  node scripts/seo-tags.mjs
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(process.cwd());
const WWW = join(ROOT, 'www');
const GAMES = join(WWW, 'src/games');

/**
 * The canonical origin. **Always prod, even in the dev build.**
 *
 * A canonical URL names the one authoritative address for a page; pointing dev's copy at
 * dev would ask search engines to index two identical sites and pick a winner. The cost
 * is that a shared *dev* link previews with the prod URL underneath, which is a
 * curiosity rather than a problem — nobody shares dev links with strangers.
 */
const ORIGIN = 'https://fonygames.guigui.fr';

/**
 * Read one string field out of a card.ts. A miss throws: a silent default would ship.
 *
 * **Both quote styles.** A single-quote-only pattern got as far as Goat Siege, whose
 * pitch is `"Shoo the neighbours' goats…"` in double quotes precisely because it
 * contains an apostrophe — exactly the value most likely to be written that way.
 */
function field(source, name, key) {
  const match = new RegExp(`${key}:\\s*(?:'([^']+)'|"([^"]+)")`).exec(source);
  if (!match) throw new Error(`could not read ${name} from the card`);
  return match[1] ?? match[2];
}

function cardOf(slug) {
  const source = readFileSync(join(GAMES, slug, 'card.ts'), 'utf8');
  return {
    title: field(source, 'title', 'title'),
    // What the illustration SHOWS. Reused as og:image:alt, which is the only place a
    // screen reader on a shared link ever hears about the picture.
    alt: field(source, 'alt', 'alt'),
  };
}

/** XML-escape, because a pitch may contain an apostrophe and one does. */
function attr(text) {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** The existing description, which stays the single source of the sentence. */
function descriptionOf(html) {
  const match = /<meta\s+name="description"\s+content="([^"]*)"/s.exec(html.replace(/\s+/g, ' '));
  if (!match) throw new Error('no meta description');
  return match[1].trim();
}

function titleOf(html) {
  const match = /<title>([^<]*)<\/title>/.exec(html);
  if (!match) throw new Error('no title');
  return match[1].trim();
}

/** Everything between the markers, so re-running replaces rather than duplicates. */
const OPEN = '    <!-- SEO:START — generated by scripts/seo-tags.mjs, see docs/specs/seo.md §3 -->';
const CLOSE = '    <!-- SEO:END -->';

function block(page) {
  const lines = [
    OPEN,
    `    <link rel="canonical" href="${page.url}" />`,
    '    <meta property="og:type" content="website" />',
    '    <meta property="og:site_name" content="FonyGames" />',
    `    <meta property="og:title" content="${attr(page.title)}" />`,
    `    <meta property="og:description" content="${attr(page.description)}" />`,
    `    <meta property="og:url" content="${page.url}" />`,
    `    <meta property="og:image" content="${page.image}" />`,
    '    <meta property="og:image:width" content="1200" />',
    '    <meta property="og:image:height" content="630" />',
    `    <meta property="og:image:alt" content="${attr(page.imageAlt)}" />`,
    '    <meta name="twitter:card" content="summary_large_image" />',
    '    <script type="application/ld+json">',
    ...JSON.stringify(page.jsonLd, null, 2)
      .split('\n')
      .map((l) => `      ${l}`),
    '    </script>',
    CLOSE,
  ];
  return lines.join('\n');
}

function inject(file, page) {
  let html = readFileSync(file, 'utf8');
  const generated = block(page);

  if (html.includes(OPEN)) {
    const start = html.indexOf(OPEN);
    const end = html.indexOf(CLOSE) + CLOSE.length;
    html = html.slice(0, start) + generated + html.slice(end);
  } else {
    // After the icon link, so the head reads: meta, title, description, then this.
    const anchor = html.indexOf('    <link rel="icon"');
    if (anchor === -1) throw new Error(`${file} has no icon link to anchor to`);
    const eol = html.indexOf('\n', anchor);
    html = `${html.slice(0, eol + 1)}${generated}\n${html.slice(eol + 1)}`;
  }

  writeFileSync(file, html);
  console.log(`seo: ${file.replace(`${ROOT}/`, '')}`);
}

/* ── The hub ─────────────────────────────────────────────────────────────── */

const hubFile = join(WWW, 'index.html');
const hubHtml = readFileSync(hubFile, 'utf8');

inject(hubFile, {
  title: titleOf(hubHtml),
  description: descriptionOf(hubHtml),
  url: `${ORIGIN}/`,
  image: `${ORIGIN}/og/hub.png`,
  imageAlt: 'Four FonyGames illustrations: a cat chasing mice, a goat at a fence, a sling-puck board and a spilling drop',
  jsonLd: {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'FonyGames',
    url: `${ORIGIN}/`,
    description: descriptionOf(hubHtml),
  },
});

/* ── One page per built game ─────────────────────────────────────────────── */

// The directories under www/ that are real pages, discovered rather than listed: a game
// page that existed and was missed would silently ship with no preview.
const pages = readdirSync(WWW, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .filter((name) => existsSync(join(WWW, name, 'index.html')))
  // The admin centre is deliberately not indexable and carries its own noindex.
  .filter((name) => name !== 'ops-placeholder')
  .sort();

for (const slug of pages) {
  const file = join(WWW, slug, 'index.html');
  const html = readFileSync(file, 'utf8');
  const card = cardOf(slug);

  inject(file, {
    title: titleOf(html),
    description: descriptionOf(html),
    url: `${ORIGIN}/${slug}/`,
    image: `${ORIGIN}/og/${slug}.png`,
    imageAlt: card.alt,
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'VideoGame',
      name: card.title,
      url: `${ORIGIN}/${slug}/`,
      image: `${ORIGIN}/og/${slug}.png`,
      description: descriptionOf(html),
      // What the product actually is, in the vocabulary a crawler understands.
      applicationCategory: 'Game',
      gamePlatform: 'Web browser',
      operatingSystem: 'Any (mobile web browser)',
      playMode: 'MultiPlayer',
      // No install, no account, no money. Stated rather than implied, because it is the
      // single most persuasive fact about the product.
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' },
    },
  });
}

/* ── The sitemap ─────────────────────────────────────────────────────────── */

/*
 * Static for now, and correct for now: no game is hidden, so the full list is the true
 * list. Once the operator can hide a game at runtime this has to become `sitemap.php`,
 * because a sitemap advertising a page the server will not serve is worse than no
 * sitemap (docs/specs/seo.md §2).
 *
 * `lastmod` is deliberately absent. It would have to come from somewhere, and the two
 * available sources are both wrong: a build timestamp says every page changed on every
 * deploy, and a git mtime does not survive a checkout. An absent lastmod is honest; a
 * wrong one teaches a crawler to ignore the field.
 */
const urls = [`${ORIGIN}/`, ...pages.map((slug) => `${ORIGIN}/${slug}/`)];
writeFileSync(
  join(WWW, 'public/sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((url) => `  <url><loc>${url}</loc></url>`).join('\n')}
</urlset>
`,
);

console.log(`seo: ${pages.length + 1} pages tagged, sitemap.xml written`);
