<?php

declare(strict_types=1);

/**
 * "A round of this game just finished." The one public write in the whole API.
 * Spec: docs/specs/backoffice.md §7 · docs/database.md §3
 *
 * The Durable Object owning a room calls this when a round ends with a winner
 * (`worker/plays.ts`). It is the sanctioned shape of the topology in database.md §3 —
 * gameplay never touches MySQL, PHP does, and the DO reaches PHP over HTTPS.
 *
 * ## Why it is not an action on index.php
 *
 * Everything in `index.php` is privileged, and the whole file is deployed under the secret
 * `ADMIN_PATH` directory. The Worker cannot know that path — it is a secret precisely so
 * crawlers cannot find it — and giving it one would spend the hidden path on a counter.
 * So this is its own endpoint, at a fixed public URL, holding exactly one capability.
 *
 * ## What stops it being a vandalism tool
 *
 * **The catalogue is the allowlist.** Only a slug the build actually rendered a card for
 * can be counted, so nothing here can create rows, and the table stays one row per game
 * however this endpoint is abused. That bounds the damage to the ordering of the hub.
 *
 * **`plays_token`, when configured, is required.** Set it in `config.php` and as the
 * Worker's `PLAYS_TOKEN` secret and only the Worker can count. Left empty — which is the
 * state of a host that has not been given the secret — the endpoint is open, and the worst
 * anyone can do is make their favourite game wear HOT. That is a deliberate trade: a
 * counter that needs a secret before it counts anything at all is a feature that silently
 * does nothing on every host where the operator has not been through the deploy yet.
 *
 * It writes ONE column of ONE row and leaves no audit trail: this is not a flag change,
 * and the change log is for decisions the operator made.
 */

require_once __DIR__ . '/lib/App.php';
require_once __DIR__ . '/lib/Flags.php';

/** JSON out, never cached. */
function answer(int $status, array $body): never
{
    http_response_code($status);
    header('Content-Type: application/json; charset=utf-8');
    header('Cache-Control: no-store');
    echo json_encode($body, JSON_UNESCAPED_SLASHES);
    exit;
}

/*
 * An uncaught throwable is an empty 500 on any host with display_errors off, and the
 * caller of this endpoint is a Worker that will never be watched by a human. A named
 * failure is the difference between "the count is not landing" and no information at all.
 */
set_exception_handler(static function (Throwable $e): void {
    answer(500, ['error' => 'unavailable', 'kind' => get_class($e)]);
});

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') !== 'POST') {
    answer(405, ['error' => 'POST only']);
}

$app = App::boot(__DIR__);

if (!$app->configured()) {
    answer(503, ['error' => 'this host has no database configured']);
}

$token = (string) ($app->config['plays_token'] ?? '');
if ($token !== '') {
    // `hash_equals`, not `===`: this is a secret comparison, and the timing of a short-
    // circuiting compare leaks the prefix. Cheap here, and the habit is the point.
    $sent = (string) ($_SERVER['HTTP_X_PLAYS_TOKEN'] ?? '');
    if (!hash_equals($token, $sent)) {
        answer(401, ['error' => 'no']);
    }
}

$raw = file_get_contents('php://input');
$body = ($raw === false || $raw === '') ? [] : json_decode($raw, true);
$slug = Flags::slug(is_array($body) && is_string($body['slug'] ?? null) ? $body['slug'] : null);

if ($slug === null) {
    answer(400, ['error' => 'bad slug']);
}

/*
 * The allowlist: the slugs the build rendered cards for.
 *
 * `_hub/cards.php` is generated by `scripts/ssr.mjs` and sits beside `api/` in the web
 * root. Its absence means this host was deployed without the hub build, in which case
 * there is no catalogue to be part of and nothing to count — refused rather than guessed,
 * because guessing here is what would let this endpoint invent rows.
 */
$built = @include __DIR__ . '/../_hub/cards.php';
$catalogue = is_array($built) && is_array($built['order'] ?? null) ? $built['order'] : [];

if ($catalogue === []) {
    answer(503, ['error' => 'this host has no rendered catalogue, so nothing can be counted']);
}

if (!in_array($slug, $catalogue, true)) {
    // 404 rather than 400: the request was well formed, the game does not exist here.
    answer(404, ['error' => 'no such game']);
}

try {
    $result = $app->flags()->count($slug);
} catch (PDOException $e) {
    // 503, not 500 — the request was fine and the dependency is not. No detail: this
    // endpoint is public, and a PDO message names the database user and host.
    answer(503, ['error' => 'the database is not reachable']);
}

// `published` is reported rather than assumed, exactly as a flag write does: the hub reads
// the FILE, so a counted round that did not reach flags.json has not happened yet as far
// as any player is concerned.
answer(200, ['ok' => true, 'plays' => $result['plays'], 'published' => $result['published']]);
